### ISSUE TITLE
Cairo on MacOS draws nothing

### ISSUE THREAD

**Issue by falkTX** [lv2/pugl#105]
Seems cairo on macOS has been broken for a long time, I thought it was me doing something wrong on DPF side but I just built the pugl cairo examples and still end up with an empty window.

Running macOS 12.6.1, cairo installed via homebrew. Using f6f0ecfa0aa9872a582e22f2b839d500105aafa1

Build log:

```
% meson build
The Meson build system
Version: 1.1.1
Source dir: /Users/falktx/Source/DISTRHO/DPF/dgl/src/pugl-upstream
Build dir: /Users/falktx/Source/DISTRHO/DPF/dgl/src/pugl-upstream/build
Build type: native build
Project name: pugl
Project version: 0.5.3
C compiler for the host machine: ccache cc (clang 14.0.0 "Apple clang version 14.0.0 (clang-1400.0.29.202)")
C linker for the host machine: cc ld64 820.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
C++ compiler for the host machine: ccache c++ (clang 14.0.0 "Apple clang version 14.0.0 (clang-1400.0.29.202)")
C++ linker for the host machine: c++ ld64 820.1
Objective-C compiler for the host machine: ccache cc (clang 14.0.0)
Objective-C linker for the host machine: cc ld64 820.1
Objective-C++ compiler for the host machine: ccache c++ (clang 14.0.0)
Objective-C++ linker for the host machine: c++ ld64 820.1
Library dl found: YES
Run-time dependency appleframeworks found: YES (foundation, corevideo)
Library m found: YES
Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
Run-time dependency gl found: YES
Run-time dependency cairo found: YES 1.16.0
Compiler for C supports arguments -Wno-documentation: YES 
Compiler for C supports arguments -Wno-documentation-unknown-command: YES 
Compiler for C supports arguments -Wno-reserved-identifier: YES 
Run-time dependency vulkan found: NO (tried pkgconfig and system)
Compiler for Objective-C++ supports arguments -Wno-c++98-compat: YES 
Compiler for Objective-C++ supports arguments -Wno-c++98-compat-pedantic: YES 
Compiler for Objective-C++ supports arguments -Wno-deprecated-declarations: YES 
Compiler for Objective-C++ supports arguments -Wno-direct-ivar-access: YES 
Configuring Info.plist using configuration
Configuring Info.plist using configuration
Configuring Info.plist using configuration
Configuring Info.plist using configuration
Configuring Info.plist using configuration
Configuring Info.plist using configuration
Configuring Info.plist using configuration
Configuring Info.plist using configuration
Program doxygen found: NO
Program sphinxygen found: NO
Program sphinx-build found: NO
Downloading sphinxygen source from https://download.drobilla.net/sphinxygen-1.0.0.tar.gz
Download size: 13894
Downloading: ..........

Executing subproject sphinxygen 

sphinxygen| Project name: sphinxygen
sphinxygen| Project version: 0.0.1
sphinxygen| Program python3 (argparse, textwrap, xml.etree.ElementTree) found: YES (/usr/local/bin/python3) modules: argparse, textwrap, xml.etree.ElementTree
sphinxygen| Program sphinxygen found: YES (/Users/falktx/Source/DISTRHO/DPF/dgl/src/pugl-upstream/subprojects/sphinxygen-1.0.0/src/sphinxygen/sphinxygen.py)
sphinxygen| Build targets in project: 31
sphinxygen| Subproject sphinxygen finished.

Program sphinxygen found: YES (overridden)
Build targets in project: 31
NOTICE: Future-deprecated features used:
 * 0.64.0: {'copy arg in configure_file'}

pugl 0.5.3

  Configuration
    Platform      : mac

  Backends
    Cairo         : YES
    OpenGL        : YES
    Stub          : YES
    Vulkan        : NO

  Components
    Tests         : YES
    Examples      : YES
    Documentation : NO

  Directories
    Install prefix: /usr/local
    Headers       : /usr/local/include
    Libraries     : /usr/local/lib
    Executables   : /usr/local/bin

  Subprojects
    sphinxygen    : YES

Found ninja-1.11.1 at /usr/local/bin/ninja
```

output of otool:

```
% otool -L ./build/examples/pugl_cairo_demo.app/MacOS/pugl_cairo_demo
./build/examples/pugl_cairo_demo.app/MacOS/pugl_cairo_demo:
	@rpath/libpugl_mac-0.0.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libpugl_mac_cairo-0.0.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
	/usr/local/opt/cairo/lib/libcairo.2.dylib (compatibility version 11603.0.0, current version 11603.0.0)
```

When running `pugl_cairo_demo` this is what I see on screen:

<img width="276" alt="image" src="https://github.com/lv2/pugl/assets/1334853/4e101a12-b540-44e8-8d25-f4f13f089652">

**Comment by falkTX** [comment]
I think I found the culprit, the line https://github.com/lv2/pugl/blob/f6f0ecfa0aa9872a582e22f2b839d500105aafa1/src/mac_cairo.m#L99

According to the example in https://cairographics.org/manual/cairo-Quartz-Surfaces.html we should use

```
CGContextTranslateCTM (cgContext, 0.0, height);
```

while current pugl uses `-height`as the 3rd argument there.
is there a reason for this? maybe a leftover thing from OpenGL setup where Y/height coordinates are inverted?

with that change I get stuff drawn on the window:

<img width="268" alt="image" src="https://github.com/lv2/pugl/assets/1334853/520b0673-8fdb-45c1-9092-31a846ca774a">

**Comment by falkTX** [comment]
the pugl example is a bit simplistic (understandably) so I went to try the fix with something more involved.
confirmed to work correctly with https://github.com/DISTRHO/elements-template-plugin

<img width="604" alt="image" src="https://github.com/lv2/pugl/assets/1334853/0fb5d02e-c929-46d5-a9c1-e41ed251a2c6">

**Comment by drobilla** [comment]
Hm.  The cairo demo on current main works fine for me on MacOS 13.6.  I was previously working on MacOS 11 and it worked there, too.  There's been some issues specifically around embedding somewhat recently, but programs not working is a new one as far as I know.

That offset code is 3 years old and quite a lot of people have used it successfully.  IIRC the negative offsets are to deal with the inverted Y axis.  Your change breaks it for me.

Where is your cairo from?

**Comment by falkTX** [comment]
I tried with both homebrew and self-built cairo as part of https://github.com/DISTRHO/PawPaw

I never had pugl and cairo working on any of my systems, though I mostly test on a M1 machine so maybe that is the difference? Actually seems weird to me that it works as-is for you, rather than the contrary.

**Comment by drobilla** [comment]
This is on an M2 with homebrew's cairo.  Machine is fresh out of the box with nothing screwed with aside from installing XCode and homebrew.  I was previously using a self-built cairo on Intel.

**Comment by falkTX** [comment]
macbook with retina display? just in case high-dpi has something to do with it... the tests I did above were with an old intel macbook, so it has high-dpi stuff in place.

**Comment by drobilla** [comment]
Both Macbook Pros using the built-in "Retina" display.

**Comment by mfisher31** [comment]
Repro'd in `main`

<img width="356" alt="cario-blank" src="https://github.com/lv2/pugl/assets/880111/56c28b9c-107a-4ffc-b9cc-7dc5bc01af50">

<img width="599" alt="system-info" src="https://github.com/lv2/pugl/assets/880111/c637340b-c121-4978-8036-bd71346ab48a">

```bash
mfisher@MacMini-M1 pugl % meson setup build
The Meson build system
Version: 0.63.0
Source dir: /Users/mfisher/workspace/lad/pugl
Build dir: /Users/mfisher/workspace/lad/pugl/build
Build type: native build
Project name: pugl
Project version: 0.5.3
C compiler for the host machine: ccache cc (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")
C linker for the host machine: cc ld64 711
Host machine cpu family: aarch64
Host machine cpu: arm64
C++ compiler for the host machine: ccache c++ (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")
C++ linker for the host machine: c++ ld64 711
Objective-C compiler for the host machine: ccache cc (clang 13.0.0)
Objective-C linker for the host machine: cc ld64 711
Objective-C++ compiler for the host machine: ccache c++ (clang 13.0.0)
Objective-C++ linker for the host machine: c++ ld64 711
Library dl found: YES
Run-time dependency appleframeworks found: YES (foundation, corevideo)
Library m found: YES
Found pkg-config: /opt/homebrew/bin/pkg-config (0.29.2)
Run-time dependency gl found: YES
Run-time dependency cairo found: YES 1.16.0
Compiler for C supports arguments -Wno-documentation: YES 
Compiler for C supports arguments -Wno-documentation-unknown-command: YES 
Compiler for C supports arguments -Wno-reserved-identifier: NO 
Run-time dependency vulkan found: NO (tried pkgconfig and system)
Compiler for Objective-C++ supports arguments -Wno-c++98-compat: YES 
Compiler for Objective-C++ supports arguments -Wno-c++98-compat-pedantic: YES 
Compiler for Objective-C++ supports arguments -Wno-deprecated-declarations: YES 
Compiler for Objective-C++ supports arguments -Wno-direct-ivar-access: YES 
Configuring Info.plist using configuration
Configuring Info.plist using configuration
Configuring Info.plist using configuration
Configuring Info.plist using configuration
Configuring Info.plist using configuration
Configuring Info.plist using configuration
Configuring Info.plist using configuration
Configuring Info.plist using configuration
Program doxygen found: YES (/opt/homebrew/bin/doxygen)
Program sphinxygen found: NO
Program sphinx-build found: YES (/Users/mfisher/Library/Python/3.8/bin/sphinx-build)
Downloading sphinxygen source from https://download.drobilla.net/sphinxygen-1.0.0.tar.gz
Downloading: 100%|████████████████████████████████████| 13894/13894 [00:00<00:00, 4502136.88bytes/s]

Executing subproject sphinxygen 

sphinxygen| Project name: sphinxygen
sphinxygen| Project version: 0.0.1
sphinxygen| Program python3 (argparse, textwrap, xml.etree.ElementTree) found: YES (/opt/homebrew/bin/python3) modules: argparse, textwrap, xml.etree.ElementTree
sphinxygen| Program sphinxygen found: YES (/Users/mfisher/workspace/lad/pugl/subprojects/sphinxygen-1.0.0/src/sphinxygen/sphinxygen.py)
sphinxygen| Build targets in project: 31
sphinxygen| Subproject sphinxygen finished.

Program sphinxygen found: YES (overridden)
Configuring conf.py using configuration
Configuring Doxyfile using configuration
Build targets in project: 35

pugl 0.5.3

  Configuration
    Platform      : mac

  Backends
    Cairo         : YES
    OpenGL        : YES
    Stub          : YES
    Vulkan        : NO

  Components
    Tests         : YES
    Examples      : YES
    Documentation : YES

  Directories
    Install prefix: /usr/local
    Headers       : /usr/local/include
    Libraries     : /usr/local/lib
    Executables   : /usr/local/bin

  Subprojects
    sphinxygen    : YES

Found ninja-1.10.2 at /opt/homebrew/bin/ninja
mfisher@MacMini-M1 pugl % meson compile -C build
ninja: Entering directory `/Users/mfisher/workspace/lad/pugl/build'
[73/74] Generating doc/c/singlehtml with a custom command
/Users/mfisher/Library/Python/3.8/lib/python/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (5.0.0)/charset_normalizer (2.0.1) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
/Users/mfisher/workspace/lad/pugl/build/doc/c/deployment.rst:36: WARNING: Pygments lexer name 'meson' is not known
[74/74] Generating doc/c/html with a custom command
/Users/mfisher/Library/Python/3.8/lib/python/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (5.0.0)/charset_normalizer (2.0.1) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
/Users/mfisher/workspace/lad/pugl/build/doc/c/deployment.rst:36: WARNING: Pygments lexer name 'meson' is not known
mfisher@MacMini-M1 pugl % ./build/examples/pugl_cairo_demo.app/MacOS/pugl_cairo_demo
```

**Comment by mfisher31** [comment]
Monitor I have is 4k: https://www.viewsonic.com/eu/products/sheet/VX2475Smhl-4K

**Comment by mfisher31** [comment]
I noticed in the same docs: say "If the CGContext is in the Quartz coordinate space (with the origin at the bottom left), then it should be flipped before this function is called"  And it then recommends doing the flip with two function calls, not simply flipping to -height.

```c
CGContextTranslateCTM (cgContext, 0.0, height);   // no -height
CGContextScaleCTM (cgContext, 1.0, -1.0);             // the real flip as recommended?
```

**Comment by mfisher31** [comment]
> MacOS 13.6. I was previously working on MacOS 11

See comment in #106 - @falkTX and I both can repro v12 macs.  Not sure what my laptop version is but I'll check that one in a bit.

**Comment by drobilla** [comment]
Being like this for 12 only would be... quite something, although I wouldn't put it past Apple these days 🤷

I dunno.  I can try on an external monitor when I get home, which is maybe a relevant variable, but I'm away right now.  Try a different fix I guess, one will stick eventually.

**Comment by mfisher31** [comment]
Well... my macbook is version 11... but home brew wants me to update Xcode and is failing.  Unfortunately this machine is a build agent for a handful of projects that I can't risk breaking.  

And yeah, to be a 12 specific problem is unlikely, I just noticed we're on 12 and you're not.

My new theory is that somehow the `sizePt.height` is negative for some reason on @drobilla 's machines.

```c
// ....
const CGSize sizePt = CGContextConvertSizeToUserSpace(context, sizePx);
if (sizePt.height < 0)
  sizePt.height = -sizePt.height

// ....

```

^^^ I'd put money that fixes it across the board, but I can't test without risk of breaking the build bots.

**Comment by mfisher31** [comment]
Ok, might have a winner:  I pulled @falkTX 's branch and added a few things:
https://github.com/lv2/pugl/compare/main...mfisher31:pugl:fix-cairo-quartz-translate

First, I fixed the logical scaling of the demo itself by using `puglGetScaleFactor`  (couldn't resist) and second, apply the inverse scale factor to the CG translate call.  Visually it doesn't really change anything for, aside from the sizing.  Hopefully this works for @drobilla  too.

**Comment by drobilla** [comment]
> My new theory is that somehow the sizePt.height is negative for some reason on @drobilla 's machines

Yep, it is.

**Comment by drobilla** [comment]
Could just... ram an `fabs` in there I suppose, but why is this inverting on some machines and not others?

**Comment by falkTX** [comment]
also it does not happen with opengl, I always had that working correctly on macOS, issue is only with cairo.

I can try with vulkan, if there is a demo, but pugl does not have that enabled by default on macOS. do we need to install something extra?

**Comment by drobilla** [comment]
This code is in the Cairo backend, so it won't affect anything else.  Vulkan unfortunately stopped working on MacOS.  I need to update the demo to "register" with the new compatibility extension required to make things work on non-conformant implementations (like MoltenVK on Metal).

I'd like to understand why mirroring is happening _sometimes_ here, but ultimately if

    CGContextTranslateCTM(context, 0.0, fabs(sizePt.height));
    CGContextScaleCTM(context, scale, -scale);

works for both of you as well, well, that's a fix.

**Comment by drobilla** [comment]
Try with `-r`, and what scale factor is reported on these machines?

**Comment by drobilla** [comment]
Well I can't figure out _why_ this is acting weird, so maybe we can just avoid it entirely... try e33b2f6

**Comment by drobilla** [comment]
No ability to reproduce and no feedback for 6 months, so I'm assuming the above change fixed the issue.

**Comment by falkTX** [comment]
FYI I got no more reports of breakages either.
