### ISSUE TITLE
Windows: puglGetProcAddress calls wrong function if UNICODE macro is defined

### ISSUE THREAD

**Issue by theuser27** [lv2/pugl#124]
Hello everyone,
I'm new to this library and tried to configure a build from scratch (for opengl shader demo on Windows 10 with Visual Studio 2022) since I didn't have meson installed and by default empty projects are automatically configured with Unicode character set which sets the UNICODE and _UNICODE macros. So upon trying to run the demo I got tripped up by a call in win_gl.c (puglGetProcAddress) to GetModuleFileName which was defined as GetModuleFileNameW and the parameter passed in was a normal char * which gets interpreted as wide char *. Because of that the function failed and I couldn't get a handle to opengl32.dll to get glGetString function pointer.
After doing a short search I found that there's a different instance in win.c (puglRegisterWindowClass) where the GetModuleHandleEx macro might be susceptible to the same error. 
I would suggest choosing a specific version (either -A or -W with appropriate strings) of these and other functions macros to avoid such errors.

Cheers

**Comment by drobilla** [comment]
Whenever I'm feeling down, I remember that at least I've never screwed anything up nearly as badly as MS did Unicode.

**Comment by drobilla** [comment]
> I would suggest choosing a specific version (either -A or -W with appropriate strings) of these and other functions macros to avoid such errors.

It's not that easy, but it's not _that_ terrible to deal with: 996196c.

**Comment by drobilla** [comment]
Note that the API is always UTF-8, so you're probably going to have a bad time doing this for other reasons.

It's generally expected that applications aren't dealing with the win32 API directly much if at all (being the point of pugl), so I recommend using the https://utf8everywhere.org/ philosophy in your own code.

**Comment by drobilla** [comment]
90e05c9 goes a little further and supports building both with and without `UNICODE`.

**Comment by theuser27** [comment]
Very late reply but thanks for fixing this one :-). It was a source of really confusing runtime errors since it would sometimes work and others not.
