### ISSUE TITLE
Fall-back to basic pixel format if wglChoosePixelFormat() failed

### ISSUE THREAD

**Issue by 7890** [lv2/pugl#25]
Instead of returning with an error here:
https://github.com/drobilla/pugl/blob/196d8d2943e628bc53dc21f34859ad2740ef1142/pugl/detail/win_gl.c#L165
I found that continuing equal to the else() clause 
https://github.com/drobilla/pugl/blob/196d8d2943e628bc53dc21f34859ad2740ef1142/pugl/detail/win_gl.c#L170
instead of returning will allow programs to work that would otherwise not. Replacing the return with
```
// Modern extensions not available, use basic pixel format
impl->pfd  = fakePfd;
impl->pfId = fakePfId;
```
makes a difference.

**Comment by drobilla** [comment]
Applications that ask for a particular pixel format and don't get it need to know that.  They can retry with a different one if they want.

**Comment by 7890** [comment]
Ok, fair enough. However 
`surface->procs.wglChoosePixelFormat(..)`
can return true with numFormats=0 (no matching format found). It looks like this case isn't handled right now.
