### ISSUE TITLE
puglSetTransientFor()

### ISSUE THREAD

**Issue by 7890** [lv2/pugl#26]
From what I understand the function `puglSetTransientFor()` exposed in pugl.h is implemented only in x11.c.
Obviously programs running on platforms other than Linux will fail to call this function.
I don't know if Windows and/or OSX know a similar concept, at least it would not hurt to have dummy implementations for other platforms or even better add similar functionality.
On Linux, it allows to sort of tell that a window is a child of another window, so that eg. minimize/maximize will consider both windows.
Does that make sense?

**Comment by drobilla** [comment]
53d8fe0c19408a54165f6422319be8139758a5b2
