### ISSUE TITLE
missing documents in the DOC directory ??

### ISSUE THREAD

**Issue by ffred** [lv2/pugl#31]
Hi,
in the doc directory, the header.html file let me think that there should also be there a few more files, like index.html, modules.html, namespaces.html, annotated.html, functions.html & files.html...?
are they available anywhere else, and why not here ?

[edit] sorry, just saw the link at the bottom of the front readme for the online documentation.
but why keep a DOC directory with just a few files with no interest then ? they should be all there or nothing at all....
but I got the doc via the link now, so will be able to look more into pugl.
thanks.

**Comment by drobilla** [comment]
?

The documentation has to be generated from something...
