### ISSUE TITLE
shader demos fail

### ISSUE THREAD

**Issue by dromer** [lv2/pugl#39]
First one fails because of missing shader files:
```
pugl/build$ ./pugl_shader_demo 
error: Failed to open 'shaders/header_330.glsl'
Segmentation fault
```
Simply moving `shaders/header_330.glsl` to `build/shaders/` fixes this.

The other one however:
```
pugl/build$ ./pugl_vulkan_cxx_demo
Using instance extension: VK_KHR_surface
Using instance extension: VK_KHR_xlib_surface
Using instance extension: VK_EXT_debug_report
Present mode:             FIFO
Resize present mode:      Immediate
error: Failed to load shaders (Initialization failed)
```
Doesn't work after moving all the shader files to the subdir.
Didn't look any further on the why yet.

**Comment by drobilla** [comment]
You need to run them from the top level directory, not from within build.

I have a branch where I am changing this so they can run from wherever, and also install, but that's the current situation on master.

**Comment by dromer** [comment]
ah! that was not clear to me from the instructions :)
I just assumed I had to go into the build dir to run them (as is typical for most projects afaik).
