### ISSUE TITLE
GCC version

### ISSUE THREAD

**Issue by sjaehn** [lv2/pugl#43]
I received a bug report for the Pugl code in B.SEQuenzr: https://github.com/sjaehn/BSEQuencer/issues/28

Pugl uses enumerator attributes that are not supported by older gcc versions (version < 6 (2016)). Clang supports this already even longer. A gcc5 user reported a compile error there: https://github.com/lv2/pugl/blob/master/include/pugl/pugl.h#L195 (and following lines) .

Does it make sense to check for `__GNUC__ >= 6` in line 37? But then ALL `__attribute__((deprecated("Use " rep)))` are gone. Not only the conflicting enumerator attributes.

**Comment by drobilla** [comment]
I just removed them in 1ff4f74.  The whole deprecated API should be removed soon anyway.
