### ISSUE TITLE
Allow static PUGL_API use

### ISSUE THREAD

**Issue by falkTX** [lv2/pugl#50]
Opening issue for comments.

I would like to have PUGL_API be empty, so pugl symbols are visible.
Right now pugl has the following code:

```
#if defined(_WIN32) && !defined(PUGL_STATIC) && defined(PUGL_INTERNAL)
#  define PUGL_API __declspec(dllexport)
#elif defined(_WIN32) && !defined(PUGL_STATIC)
#  define PUGL_API __declspec(dllimport)
#elif defined(__GNUC__)
#  define PUGL_API __attribute__((visibility("default")))
#else
#  define PUGL_API
#endif
```

When using gcc with `-fvisibility=hidden`, this macro will override this and set pugl symbols as default/visible.

Is there a good reason for this? Can't we simply have a `#ifndef PUGL_API` that allows developers to customize this behaviour ("use at your own risk" kinda deal).
Thanks

**Comment by drobilla** [comment]
`PUGL_STATIC` in the GCC case would also probably be fine, but allowing it to be whatever doesn't hurt anything.  Fixed in 84596ee.
