### ISSUE TITLE
"made with pugl" screenshot gallery?

### ISSUE THREAD

**Issue by falkTX** [lv2/pugl#53]
As pugl moves towards a new version, and the whole lv2kit coming too, it might be a good idea to have a showcase of plugin UIs that use pugl as backend.

As a start, feel free to use anything from DPF.
So https://github.com/DISTRHO/DPF-Plugins/ and https://github.com/DISTRHO/DPF provide a bunch of them.

**Comment by drobilla** [comment]
Pugl doesn't look like anything, and I don't want confused people judging it based on screenshots that don't really have anything to do with it.
