### ISSUE TITLE
Allow resizing without changing position

### ISSUE THREAD

**Issue by falkTX** [lv2/pugl#64]
Current pugl API has a setFrame only which, at least on macOS, re-sets the X and Y position of the UI.
While this could be worked around by fetching x/y pos before changing the frame (or get notifications about such position changes) most of the time plugins have no interest on changing x/y offset at all.

Having a way to only change the size without changing the position is handy and helps to avoid the issues described above.

Related DPF issue at https://github.com/DISTRHO/DPF/issues/198

**Comment by drobilla** [comment]
AFAIK X11 has no such API, so Pugl is just making you do what needs to be done.  You could make the same argument for the size as well - sometimes, you need to get the original size before you can figure out the new one.  `puglGetFrame` will get you everything, and you can do what you want.

Is there a concrete problem with this API that isn't trivially avoidable?

**Comment by falkTX** [comment]
X11 for sure has this, `XResizeWindow`

The issue could be the host changing the view x/y without us knowing, at some point I was a bit tired with all the debugging and just changed the code to dont deal with x/y at all and only handle the size, that resolves the issue and makes sure it doesn't happen again.

**Comment by drobilla** [comment]
Fair enough.

I don't understand how this could be a long and frustrated process with giving up at the end though.  Why is this any harder than puglGetFrame, change stuff, puglSetFrame?

**Comment by falkTX** [comment]
The get-frame did not get the offset as set by the host, at least in my tests on macOS and reaper.
I was trying to find a way around it, but my macOS API knowledge was not enough for the task.

**Comment by drobilla** [comment]
I see.  _That_ is certainly an issue.

**Comment by drobilla** [comment]
Where are you calling that puglGetFrame?

**Comment by falkTX** [comment]
> Where are you calling that puglGetFrame?

not sure what you mean..

If I want to change the size I need to get the frame first, change width and height and set frame then.

but maybe you mean something else...?

**Comment by drobilla** [comment]
Where, as in at what point in the code are you doing that?  In main?  How early?  In an event handler?  While handling which event?  Did stuff happen (i.e. events received) when the host repositioned the plugin?  etc

I don't see an obvious code path where the position is wrong, so I need more information to try and figure out what's going on.  Maybe jam `printEvent` from the pugl examples in there to get a nice log of everything that happens.

**Comment by falkTX** [comment]
as I said, the host (reaper) changes the plugin window offset. and puglGetFrame (or similar call) does not seem to know about it.

my resizing is always on main thread, can happen anytime during the UI lifecycle, usually triggered by a mouse or keyboard event. I dont think logs will help here, but can try later on.

**Comment by drobilla** [comment]
Logs may determine what, if anything, happens when the host moves the child window.  That is the time that pugl needs to update the frame position, but apparently isn't.  I need to know what pugl code is firing when the host repositions the window.

On MacOS, looking at the code, I would expect perhaps that it doesn't update until the next expose, because that's where that's handled, but don't see a way it could be wrong and stay that way for a long time.

**Comment by falkTX** [comment]
this will be tricky to do since reaper does the vst2 getrect+reposition every 5 seconds or so. it is constantly pushing the plugin into the proper place on a regular timer.
but sure, can try to get some logs in any case.

**Comment by drobilla** [comment]
... wat

**Comment by falkTX** [comment]
just to clarify, for some reason reaper triggers the vst2 effEditRect around every 5 seconds and sets the window size.
I guess as a way to force misbehaving plugins or something into position.
what ends up happening is flickering when a stock pugl window is resized. from being on top of reaper's controls (as triggered by pugl) to then being snapped into the correct position a tiny bit later (as triggered by reaper).

I didnt mention this before because it is not exactly relevant, and a bit confusing. but yeah, it is how reaper does things.

**Comment by drobilla** [comment]
I am not opposed to having API for setting the size given the current position, but I think the realities of the underlying APIs on some platforms means that the position being wrong at any point is going to be a problem regardless, so that needs figuring out.  Perhaps Pugl's internal storage of the position could be eliminated entirely, that would certainly be nice (as is any removal of redundant information), but I'm not sure if that's feasible.

That said, Pugl will not participate in that sort of race to the bottom.  People jamming kludges on top of kludges to "fix" this or that situation is already a huge problem, which only results in nothing working properly anywhere.  If I had a nickel for every time somebody reported "bugs" that were happening in clearly ridiculous degenerate situations, and tangentially mention that as "not exactly relevant" or whatever, I'd have a shitload of nickels :)

The ongoing elimination of the resize extension is a step in the right direction here.  If Pugl's idea of the position or size of a view is wrong, though, then a bunch of other things _will_ be broken as well.  I think we either need to make that correct, or eliminate it entirely (by always getting it from the system or whatever).

**Comment by falkTX** [comment]
I am all for removing the x/y position support from pugl.
the only times I had to use them were to center dialogs relative to other windows, stuff that in theory shouldnt be needed anyway.
maybe standalones could make use of it, to save and restore last used position but from what I have experienced this has never been very robust, as users can easily change their desktop setup in between application uses, and as you say wayland doesnt even have such a thing.

for plugins, IMO the use of position that is not 0,0 based is always very confusing and a pain to deal with.
I would be for it if pugl had some MDI or multi-view window stuff, but with pugl being 1 view = 1 window, havig position for plugins is just not very useful at all.

**Comment by drobilla** [comment]
I am too, and I was all for not adding it in the first place (I absolutely despise all window management stuff in Pugl), but I don't think that's realistic, unfortunately :/  As far as I can tell, in practice both Windows and X11 at least require this in some form or another.  Like it or not, windows do have a position, even embedded ones.  Plugins almost certainly shouldn't be messing with it, but that's a separate question.

Even for plugins, the ability to make top-level windows is the fallback that can work just about everywhere ("external UI", although as you know I think that extension is deeply wrong in the way it goes about it), in which case, we're back to needing this stuff again.

**Comment by falkTX** [comment]
pugl can always just focus on position-less plugin stuff, and if anyone wants the external ui management case, let them deal with it themselves.
having a focus and not trying to do everything can be a good thing.

**Comment by falkTX** [comment]
And speaking about X11, the things I have seen that plugins need to use all have a way to deal without x or y positions. Only the initial creation needs coordinates IIRC, but those are fine as 0,0.
Not overly familiar with win32 api, but there is a dedicated flag for not moving the window when setting the position.

The only problem I have seen on X11, is when wanting to open a menu as its own window, based on a fixed coordinate of the plugin gui (usually top left). This requires knowing if the window has an offset or not.
But since pugl does not do this frameless popup window stuff, it can be just considered out of scope.
And one can always create fake popups draw within the view anyway.

**Comment by drobilla** [comment]
No windows are position-less.  That's just not how things work.  It wouldn't reduce complexity much anyway.

> Not overly familiar with win32 api, but there is a dedicated flag for not moving the window when setting the position.

IIRC there are lies in the API about initial positioning that don't actually work, but yes, you can resize things without setting the position.

To the rest, indeed.  It would be possible to make Pugl a militantly single-view only library, and I certainly find that appealing, but that means no menus, no dialogs, no multiple "document" views, etc.  I'd be closing some whiny ticket about that every day for the rest of my life.  Removal of positioning entirely means that it would be impossible to center yourself in the parent window you're given to embed into, etc etc etc.  Position isn't really much a burden in the library at all, though multiple views certainly is.  I've considered nuking it (this would massively increase the hypothetical portability of all Pugl apps, too - not every target even _has_ windows at all), but... meh.  Here we are.

One could - and several have - made the exact same argument about resizing: not something plugins should be doing to themselves, period.  I find this argument at least as compelling as the one about position.  Not having just one or the other seems silly to me.  If we wanted to go this route of minimalism, then I think both should be thrown out, and officially designated as the host's - and only the host's - business.

**Comment by drobilla** [comment]
Also if the position is wrong, the size probably is too anyway.  It's the same event.

**Comment by falkTX** [comment]
Depending on the point of view, one is going to be more important than the other.
But generally speaking, UI size is more important than its position. We had LV2 ui:resize as feature, but not ui:reposition for a reason.

That said, in VST world the window bounds always include 4 coordinates and this was even brought again in VST3. Most plugins and hosts tend to ignore the "upper/leftmost" bounds and just substract them from the "bottom/rightmost" to get the real width/height, but the data is still there. So it must be needed on some occasions.

I am fine with pugl either way. Though still think it is nice for its API to provide methods to change only the size.
Right now with official pugl API a plugin needs to fetch frame, modify width and height, and set that frame, even if it has no need/interest on the x/y position.
While I agree we should see about the plugin always having the position being in sync with real in-use values by the host, being able to change size without position is useful, and also changing position without size too because why not. All 3 main OS APIs have ways to do this, ignoring what they might be doing behind the scenes anyway.

**Comment by drobilla** [comment]
> We had LV2 ui:resize as feature, but not ui:reposition for a reason.

Sure.  Specifically, that I gave in to the pressure and gave people their kludge hammer, despite it being obviously wrong.  That was a mistake, and the long-term consequences of it were even worse than I imagined.

As you may have noticed, I don't do that sort of thing anymore.  Even if the workaround itself is reasonable.  I may not be prescient, but I do at least learn my lessons!

**Comment by drobilla** [comment]
As far as I can tell, MacOS has no such API, only `setFrame`.  That's also - probably not coincidentally - the platform where there's a bunch of coordinate space conversion to deal with the scale factor...

So whatever this issue is can't be avoided by adding API to only set the size on MacOS, or at least, that's not necessary because internally Pugl needs to somehow know/use the right position anyway.

**Comment by falkTX** [comment]
macOS has `setFrameSize`, at least for the views.

**Comment by drobilla** [comment]
Yeah, but it's needed for the window as well.  It might be possible to better separate the two cases, though.

**Comment by drobilla** [comment]
WIP branch here: https://github.com/lv2/pugl/tree/set-size

I don't have things set up on my Mac to test embedding right now (had to reinstall), so that bit is written blind (I still need to implement the MacOS-specific meson boilerplate to make the example programs usable apps).

**Comment by drobilla** [comment]
I fixed the examples to build as working MacOS apps, and `pugl_embed_demo.app` modified to use the above functions seems to work fine (you can move/resize the embedded view around with the keyboard if it has focus).  Then again, it always did when using the whole frame.

So there is still definitely a bug here, but that API would let you avoid setting the position anyway.

I'm still not sure about the other API changes on that branch, trying to keep the bloat down but keep things clear and easy to use... the type changes aren't strictly necessary for this change, but I felt like the "double everywhere" thing was geting out of hand, especially here when it's kind of confusing to conflate frame coordinates/sizes with internal view ones.

**Comment by drobilla** [comment]
Added in 82405e8c
