### ISSUE TITLE
Add API to raise window (aka bring to front)

### ISSUE THREAD

**Issue by falkTX** [lv2/pugl#66]
pugl already has a function to give input focus, but from my testing this does not bring the window to front which is weird..
I dont recall now if the keyboard focus works or not if the window is not in front.

I have implemented this in DPF, see https://github.com/DISTRHO/DPF/blob/develop/dgl/src/pugl.cpp#L277

Feel free to add or ignore.
For standalone applications I find this quite useful

**Comment by drobilla** [comment]
The Windows case you have there is inconsistent.  Something like BringWindowToTop seems more like what the other platforms are doing.

I don't understand the documentation of SetForegroundWindow and SetActiveWindow, it is very confusing but they seem more to do with input focus than stacking.

**Comment by drobilla** [comment]
Added in 92b5ab6 as a command parameter to `puglShow`.

Sorry for the API break, there's too much behavior here to put in separate functions (the code in DPF uses functions you shouldn't normally use on both MacOS and Windows).  This way covers everything in `puglShow` and is easily extensible just in case.
