### ISSUE TITLE
XSetInputFocus on non-mapped windows can trigger a crash

### ISSUE THREAD

**Issue by falkTX** [lv2/pugl#67]
There are cases where the host gives us a window that is not yet mapped.
Or sometimes on standalones our own window is not mapped yet, likely result of a puglShow directly followed by a puglGrabFocus
Trying to give input focus here results in a crash.

I already had some code in Carla that deals with this (needed by a few plugins, for many reasons I cant explain).
So plugging this in for DPF made the crashes go away, I did not investigate the matter further.

Relevant code in question:

```
XWindowAttributes wa;
memset(&wa, 0, sizeof(wa));

if (XGetWindowAttributes(impl->display, impl->win, &wa) && wa.map_state == IsViewable) {
// safe to give focus
}
```

**Comment by drobilla** [comment]
Fixed in 17fa2a0d
