### ISSUE TITLE
Wrong default cursor under KDE

### ISSUE THREAD

**Issue by falkTX** [lv2/pugl#73]
When doing nothing with the pointer (default, `puglSetCursor` never called) or setting it to `PUGL_CURSOR_ARROW` it looks incorrect under KDE.

![Screenshot_20211215_101352](https://user-images.githubusercontent.com/1334853/146167825-96b064e3-0b78-4c7f-8ee3-f56972c8c2d3.png)
 
I have seen this before on some raw X11 applications, looks very ugly and out of place.
The cursor is supposed to look like this: (which I can still get by building pugl without `HAVE_XCURSOR` defined.

![Screenshot_20211215_101653](https://user-images.githubusercontent.com/1334853/146168103-81c0fdea-3f21-43e5-8598-e2fee7a5f353.png)

**Comment by drobilla** [comment]
Fixed in c6238d97, thanks.

I had better luck with this using the cursor theme, and "default" for the pointer one.  That way, I get matching cursors (for all the cursors) in GNOME, KDE, and Xfce.  The name situation seems like a real mess, though, so they might not work everywhere.

**Comment by falkTX** [comment]
Very nice last set of changes, thanks!
Do you have still more pending changes planned? I should give the updates a try, but perhaps better to wait until you push most of the possibly breaking changes.

**Comment by drobilla** [comment]
I dunno.  The only particularly breaking thing I have in the immediate pipeline is the `set-size` stuff.  I'm not sure if I'll merge that today... but I'm feeling bold/reckless so I probably will.

In general I've been trying to get through all the issues, but most of the ones that are left are either hard, tedious, or unclear, so will probably still be in the works for a while.

**Comment by falkTX** [comment]
fair enough, I will try to give some time/attention to the issues I reported, somewhat soon.
will need to "rebase" against latest pugl to remove the things I had in dpf that are no longer needed (went into pugl directly). but this might be nice as a way to sorta catch regressions, as things are more or less working fine with current dpf+pugl (except the copy&paste mostly)

**Comment by drobilla** [comment]
Scratch that, size stuff is merged.

Rebasing on the current master is always a good idea, it just piles up otherwise.  Other than the clipboard stuff I don't expect any particularly dramatic API changes.
