### ISSUE TITLE
wc.hInstance     = GetModuleHandle(NULL);

### ISSUE THREAD

**Issue by jjYBdx4IL** [lv2/pugl#75]
The window class is registered for the main executable image under Windows. If you have two plugin instances each statically linked with their own pugl code, that is likely to cause issues. See here:

https://github.com/glfw/glfw/issues/1395

That issue also references GLFW's solution (you can get the current function's module handle via the function's address).

**Comment by drobilla** [comment]
Fixed in a8a0fed3, thanks.
