### ISSUE TITLE
Native file dialog API?

### ISSUE THREAD

**Issue by falkTX** [lv2/pugl#78]
Mostly a question, not a request.
There is often a very handy thing plugins want but it is hard and painful to implement right - native file dialogs.

Although LV2 has ways to specify a file, it involves tying it to an lv2 patch parameter.
It also only works to open files, not save them.

So I am wondering about your thoughts on such an API.
Telling people to go use the regular tiny libs for such things (like osdialog or tinyfiledialogs) is IMO a bad idea, as they are awful for plugins:
- can block the main event loop
- fork/exec strategy on linux, which does not always work
- also on linux, requires gtk/kde extra tools (which can also change over time)

**Comment by drobilla** [comment]
I think such a thing should exist, but is way out of scope for Pugl.  If the current ones aren't good they should be fixed or replaced.

Such a library could perhaps go in lv2kit, but certainly not in Pugl itself.

Personally I like the host-mediated way anyway.  Plugins should not be saving arbitrary files.
