### ISSUE TITLE
MacOS transient parent isn't set on realize

### ISSUE THREAD

**Issue by falkTX** [lv2/pugl#79]
leaving a note for something to fix.
everytime we call `puglSetTransientParent`, `view->transientParent` is saved/cached.

when we call this when there is a window, pugl macOS code does its job as expected.
but if the window does not exist yet (view not realized), this value is ignored.
seems to me when the window is created the code should check if there was a transient parent set, and if so take care of that then.

will send a PR later if needed.
just going through the pugl changes for now and adjusting my code..

**Comment by drobilla** [comment]
Presumably fixed (if untested) in ef19bb7, thanks.

Other minor inconsistencies with transient parents also resolved, this was not a MacOS exclusive issue.
