### ISSUE TITLE
Request for a pugl/gl lv2 plugin example

### ISSUE THREAD

**Issue by lidxv0n** [lv2/pugl#82]
Hello.  Would you consider including with the examples, a simple version of plugin (such as a gui version of gain)?  I am not having luck finding any existing examples to learn from.  On my own, even though I am using PUGL_MODULE, it is spawing its own window, not updating its window, etc....all my errors, I am sure..but its because I don't know what I am doing. ;-).   I have looked at your balance.lv2 but the pugl version is very old compared to what it has evolved into.   Thanks for your consideration.  -David

**Comment by drobilla** [comment]
See duplicate https://gitlab.com/lv2/pugl/-/issues/6

Pugl itself is a general purpose library and does/will not depend on LV2, plugin examples belong in some LV2-specific project.  The current plan is to move the example plugins from "lv2" to a new SDKish meta-project "lv2kit", and port their UIs to Pugl.

There are some other projects that use more recent versions of Pugl, e.g. https://github.com/sjaehn/BAmp.  I agree a simple UI example, probably some visualization plugin, would be a good addition.

... and it'd be great if someone who isn't me would write one ;)

**Comment by falkTX** [comment]
FYI I maintain my own set of example plugins in https://github.com/DISTRHO/DPF/tree/develop/examples
They use pugl for the UI stuff, but not making use of pugl directly. The idea is to allow to use custom backends if one so wishes.
The general UI concepts (Cairo, OpenGL or Vulkan for graphics, mouse/keyboard events, timers etc) are all copied and mapped 1:1 from pugl though.
