### ISSUE TITLE
X11: Required XrmInitialize function is missing

### ISSUE THREAD

**Issue by falkTX** [lv2/pugl#84]
According to https://www.x.org/releases/X11R7.7/doc/man/man3/XrmInitialize.3.xhtml

> The XrmInitialize function initialize the resource manager. It must be called before any other Xrm functions are used.

This function is not seen in pugl code, but documentation states that it is required.

**Comment by drobilla** [comment]
Fixed in 452ac347, thanks.

**Comment by falkTX** [comment]
Nice, closing then
