### ISSUE TITLE
Inconsistent initial position between OSes

### ISSUE THREAD

**Issue by falkTX** [lv2/pugl#85]
I received some user reports of weird behaviour with builds using updated pugl, where the embed view is being offset by half its size.

Example: 
![image](https://user-images.githubusercontent.com/1334853/174458212-19e28abc-0bea-446e-9047-10d02bb8b76c.png)

After investigation I found that it is related to me no longer setting a size before realizing the view (I am only setting hints, including default).
This makes the initial width and height still be at zero during realize.
Issue appears only on Windows and macOS, not on Linux. Checking pugl code it is easy to see why.

This is on X11:
```
  if (!view->parent && !view->frame.x && !view->frame.y) {
...
    view->frame.x = (PuglCoord)((screenWidth - view->frame.width) / 2);
    view->frame.y = (PuglCoord)((screenHeight - view->frame.height) / 2);
  }
```

for macOS:
```
  if (view->frame.width == 0.0 && view->frame.height == 0.0) {
...
    view->frame.x = (PuglCoord)((screenWidthPx - view->frame.width) / 2.0);
    view->frame.y = (PuglCoord)((screenHeightPx - view->frame.height) / 2.0);
  }
```

and finally for windows:
```
  if (view->frame.width <= 0.0 && view->frame.height <= 0.0) {
...
    view->frame.x = (PuglCoord)((screenWidth - view->frame.width) / 2);
    view->frame.y = (PuglCoord)((screenHeight - view->frame.height) / 2);
  }
```

X11 is the only platform for which pugl checks if there is a parent.
This is what triggers the issue, pugl is setting a custom offset for embed views, where no such thing should be used.

As extra oddity, note how all the 3 platforms check for non-zero differently.

**Comment by drobilla** [comment]
Probably fixed in abe98d5, thanks.
