### ISSUE TITLE
Double DEPRECATED results in compiler warnings

### ISSUE THREAD

**Issue by sjaehn** [lv2/pugl#96]
https://github.com/lv2/pugl/blob/1e48f8bbfdb0f1ce2f9132d604405fb72d160d9d/include/pugl/pugl.h#L1611-L1621

The lower to typedefs link to the deprecated typedefs above and thus always result in compiler warnings. Intended? Or better directly typedef to `PuglRealizeEvent` and `PuglUnrealizeEvent`?

**Comment by drobilla** [comment]
I dunno.  Whatever?  Using the deprecated API stuff (which is just a courtesy to keep most things still compiling while I nail down the API) will, indeed, generate warnings.  That's the whole point...

Note that this stuff is going to go away entirely at some point in the hopefully not-too-distant future.  I suggest getting off the deprecated API as soon as possible, a little pain now means a lot less later.

**Comment by sjaehn** [comment]
But pugl itself shouldn't use its own deprecated symbols. Simple fix in https://github.com/lv2/pugl/pull/97

**Comment by drobilla** [comment]
Pugl itself is built without the deprecated API, it can't use any of it.  I guess I see what you mean, but having `PUGL_DISABLE_DEPRECATED` undefined be as annoying as possible is kind of a pro for me :)

Anyway, I'll apply that when my damned internet connection comes back up, thanks.

**Comment by drobilla** [comment]
Fixed in 1d62260
